### ISSUE TITLE
incorrect msg showing under user profile section

### ISSUE THREAD

**Issue by myvirusking** [lucifer1132/TalkingMind#11]
**Under user profile section "You haven't posted anything yet" message showing even if after uploading one or more post.**

> `Refer below screenshot`

![image](https://user-images.githubusercontent.com/40962900/80404775-4da58880-88df-11ea-8bf3-6655ede47b13.png)

**Comment by lucifer1132** [comment]
Solved the issue

**Comment by myvirusking** [comment]
**Issue not up to date with master**
` issue still showing on master branch`
